apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-v1
  namespace: default
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: myapp 
      version: v1
  template:
    metadata:
      labels:
        app: myapp 
        version: v1
    spec: 
      containers: 
      - name: myapp
        image: janakiramm/myapp:v1
        imagePullPolicy: IfNotPresent
        startupProbe:
          initialDelaySeconds: 20
          periodSeconds: 5
          timeoutSeconds: 10
          httpGet:
            port: 80
            scheme: HTTP 
            path: /
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 5
          timeoutSeconds: 10
          httpGet:
            port: 80
            scheme: HTTP 
            path: /
        readinessProbe:
          initialDelaySeconds: 20
          periodSeconds: 5
          timeoutSeconds: 10
          httpGet:
            port: 80
            scheme: HTTP 
            path: /
             